default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sliderui_development

test:
  <<: *default
  database: sliderui_test

staging:
  <<: *default
  database: sliderui_staging

production:
  <<: *default
  database: sliderui_production
  username: sliderui
  password: <%= ENV['sliderui_DATABASE_PASSWORD'] %>
