default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bxslider_development

test:
  <<: *default
  database: bxslider_test

staging:
  <<: *default
  database: bxslider_staging

production:
  <<: *default
  database: bxslider_production
  username: bxslider
  password: <%= ENV['BXSLIDER_DATABASE_PASSWORD'] %>
